version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=devops
    ports:
      - 3306:3306
  app:
    image : amir/spring-app
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - 8082:8082
    stdin_open: true
    tty: true
