version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'devops'
    volumes:
      - db:/var/lib/mysql
  app:
    image: amir/spring-app
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "6868:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: