version: "3.8"
services:
  app:
    image: amir/spring-app
    ports:
      - 8082:8082
    networks:
      - springapimysql-net
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: devops
      MYSQL_DATABASE: devops
networks:
  springapimysql-net:
