version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  timesheet-backend:
    depends_on:
      - mysqldb
    build: ./app
    restart: on-failure
    ports:
      - "6868:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: